### ISSUE TITLE
File not found.

### ISSUE THREAD

**Issue by Ade2nice** [dspinellis/ckjm#11]
Hello, I cloned a java based repo (https://github.com/androidannotations/androidannotations), the intention is to use CKJM for some metric calculation. I copied the cloned file folder to the build directory in the ckjm-1.9. I get the error file not found as below.

find build -name '*.class'  -print | java -jar Desktop/ckjm-1.9/build/ckjm-1.9.jar
File not found - '*.class'

What are your thoughts? can the classes be extracted from this cloned folder? I would be glad to know.

**Comment by dspinellis** [comment]
This is an error from the *find* program. You need to specify `'*.class'`
