### ISSUE TITLE
Upgrade ckjm's BCEL library version to 6.8.1 and add support for Java 11 syntax

### ISSUE THREAD

**Issue by afan0918** [dspinellis/ckjm#12]
I noticed that the current version of ckjm is using an older version of the BCEL library (6.0) and only supports Java 1.7 syntax. Since our project uses Java 11 syntax, I plan to upgrade ckjm's BCEL library version to the latest 6.8.1 and add support for Java 11 syntax.

I have performed the necessary upgrades and modifications, and conducted some testing. The new version of ckjm seems to work fine in a Java 11 environment. Now, I would like to contribute these changes to the project so that all users can benefit from them.

**Comment by dspinellis** [comment]
Great, thank you!
