### ISSUE TITLE
ckjm/wmc calculates method count, not weighted method count

### ISSUE THREAD

**Issue by jazzmuesli** [dspinellis/ckjm#9]
Running ckjm for org.jfree.data.general.DatasetUtils (or any other class, https://github.com/jfree/jfreechart/blob/master/src/main/java/org/jfree/data/general/DatasetUtils.java)  it returns wmc=58, but running https://github.com/mauricioaniche/ck on source code, I get wmc=336 and it looks indeed more like complexity-weighted method count.

I can see cm.incWmc in https://github.com/jazzmuesli/ckjm/blob/master/src/gr/spinellis/ckjm/ClassVisitor.java  is called before visiting every method, but it doesn't do any complexity-counting.

Are there any plans to fix it - or is it by design?

Thanks for the tool!

**Comment by dspinellis** [comment]
WMC is calculated according to the Chidamber and Kemerer's assumption "If all method complexities are considered to be unity, then WMC = n, the number of methods."
